name: Sync Sync.yml Every Hour
on:
  schedule:
    - cron: '0 * * * *' # Run every hour at the start of the hour
  workflow_dispatch:

jobs:
  sync:
    name: Sync Sync.yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          ref: main # Change 'main' to the appropriate branch if needed

      - name: Download sync.yml from Google Drive
        run: |
          curl -LJO "https://drive.google.com/uc?id=11fC84PfmgSXfxUg3-6noSDfOQocovs-Y&export=download"
          mv uc?id=11fC84PfmgSXfxUg3-6noSDfOQocovs-Y\&export=download sync.yml

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Clone Target Repo
        run: |
          git clone https://github.com/lagzian/TelegramV2rayCollector.git target-repo

      - name: Replace sync.yml in Target Repo
        run: |
          cp sync.yml target-repo/.github/workflows/sync.yml

      - name: Commit and Push Changes
        run: |
          cd target-repo
          git add .github/workflows/sync.yml
          git commit -m "Update sync.yml"
          git push

      - name: Cleanup
        run: |
          rm sync.yml
