name: Sync Sync.yml Every Hour
on:
  schedule:
    - cron: '0 * * * *' # Run every hour at the start of the hour
  workflow_dispatch: # Enable manual trigger

jobs:
  sync:
    name: Sync Sync.yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          ref: main # Change 'main' to the appropriate branch if needed

      - name: Delete existing sync.yml if present
        run: |
          rm -f sync.yml

      - name: Download sync.yml from Google Drive
        run: |
          curl -L "https://drive.google.com/uc?id=11fC84PfmgSXfxUg3-6noSDfOQocovs-Y&export=download" > sync.yml

      - name: Configure Git
        run: |
          git config --global user.name "lagzian"
          git config --global user.email "milad.lagzian@gmail.com"

      - name: Clone Target Repo with PAT
        run: |
          git clone https://github.com/lagzian/TelegramV2rayCollector.git target-repo
          cd target-repo
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
          git config credential.helper store # Store credentials for future use
          echo "https://github.com:${{ secrets.ACCESS_TOKEN }}@github.com" >> remote_url
          git remote set-url origin $(cat remote_url)

      - name: Replace sync.yml in Target Repo
        run: |
          cp ../sync.yml .github/workflows/sync.yml

      - name: Commit and Push Changes
        run: |
          git add .github/workflows/sync.yml
          git commit -m "Update sync.yml"
          git push

      - name: Cleanup
        run: |
          rm ../sync.yml
          rm remote_url
