name: Edit Readme

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Manual trigger

jobs:
  edit_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: lagzian/TelegramV2rayCollector
          path: repo  # Clone the repository to the "repo" directory
          persist-credentials: false
          fetch-depth: 0

      - name: Replace text in Readme2.md
        run: |
          sed -i 's/yebekhe/lagzian/g' repo/Readme2.md
          cd repo
          git config user.name "lagzian"
          git config user.email "milad.lagzian@gmail.com"
          git add Readme2.md
          git commit -m "Replace 'yebekhe' with 'lagzian'"
          git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/lagzian/TelegramV2rayCollector.git
          git push origin HEAD:main
