name: Combined Workflow2 

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:

  sync_and_notify:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install python-telegram-bot

    - name: Sync repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      id: sync
      run: |
        gh repo sync lagzian/TelegramV2rayCollector -b main --force || echo "::set-output name=exit_code::1"

    - name: Send Telegram notification  
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      if: always()
      run: |
        python - <<EOF
        import sys
        from telegram import Bot
        
        bot_token = '${{ env.TELEGRAM_BOT_TOKEN }}'
        bot = Bot(token=bot_token)
        chat_id = '${{ env.TELEGRAM_CHAT_ID }}'
        
        if sys.argv[1] == '0':
          message = '✅✅ Repository Updated Successfully! ✅✅'
        else:  
          message = '❗❗⚠️⚠️ Repository Update Failed! ⚠️⚠️❗❗'
        
        bot.send_message(chat_id=chat_id, text=message)
        EOF
        python3 - $STEPS_EXIT_CODE

  update_readme:

    needs: sync_and_notify

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: lagzian/TelegramV2rayCollector
        path: repo
        persist-credentials: false
        fetch-depth: 0

    - name: Replace text in README.md
      run: |
        sed -i 's/yebekhe/lagzian/g' repo/README.md
        cd repo
        git config user.name "lagzian"
        git config user.email "milad.lagzian@gmail.com"
        git add README.md

        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Replace 'yebekhe' with 'lagzian'"
          git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/lagzian/TelegramV2rayCollector.git
          git push origin HEAD:main
        fi
